##数据连接信息  
spring:  
    datasource:  
      type: com.alibaba.druid.pool.DruidDataSource #指定使用的数据池类
      url: "jdbc:mysql://localhost:3306/cloud_note?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true"
      username: "root"  
      password: "root"
    thymeleaf:
            cache: false
            encoding: UTF-8
            mode: HTML5
            content-type: text/html
            prefix: classpath:/templates/
            suffix: .html
    devtools:
      livereload:
        enabled: true
##增加如下配置可以避免找不到静态文件的问题
    mvc:
      static-path-pattern: /**
    resources:
      static-locations:  classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  type-aliases-package: com.elwyn.entity
server:
  context-path: /elwyn
  port: 9999
