##数据连接信息  
spring:  
    datasource:  
      type: com.alibaba.druid.pool.DruidDataSource #指定使用的数据池类
      url: "jdbc:mysql://localhost:3306/cloud_note?useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&autoReconnect=true"
      username: "root"  
      password: "root"
      validation-query: "SELECT 'X' FROM DUAL"  
      max-wait: 10000 #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制  
      max-idle: 10 #最大空闲数，数据库连接的最大空闲时间。超过空闲时间，数据库连接将被释放。设为0表示无限制  
      min-idle: 5  #最小空闲连接:连接池中容许保持空闲状态的最小连接数量,低于这个数量将创建新的连接
      max_active: 50   #连接池的最大数据库连接数。设为0表示无限制
      initial-size: 5  #初始化连接:连接池启动时创建的初始化连接数量  
      test-on-borrow: false  
      test-while-idle: true  
      remove_abandoned: true #超过removeAbandonedTimeout时间后，是否进 行没用连接（废弃）的回收（默认为false，调整为true)  
      remove_abandoned_timeout: 180 #超过时间限制，回收没有用(废弃)的连接（默认为 300秒，调整为180）  
      time-between-eviction-runs-millis: 18800  
      pool-prepared-statements: true  
      max-pool-prepared-statement-per-connection-size: 20  
      connection-properties: config.decrypt=true;druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000  
      filters: stat,wall,log4j2

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  check-config-location: true
  type-aliases-package: com.elwyn.entity